In [51]:
import numpy as np

arr=np.array([1,3,4,5])
print(arr)
print(arr.ndim)

[1 3 4 5]
1


In [52]:
import numpy as np

arr=np.array([1,3,4,5])
arr2=np.array([[2,4,5,7],[9,5,3,2]])
print(arr)
print("\n")
print(arr2)
print(arr2.ndim)

[1 3 4 5]


[[2 4 5 7]
 [9 5 3 2]]
2


In [53]:
import numpy as np

arr=np.array([1,3,4,5])
arr2=np.array([[2,4,5,7],[9,5,3,2]])
arr3=np.array([[[2,5,6],[3,5,9]],[[3,5,7],[8,3,2]]])
print(arr)
print("\n")
print(arr2)
print("\n")
print(arr3)
print(arr3.ndim)

[1 3 4 5]


[[2 4 5 7]
 [9 5 3 2]]


[[[2 5 6]
  [3 5 9]]

 [[3 5 7]
  [8 3 2]]]
3


In [6]:
import numpy as np

arr=np.array([1,3,4,5])
arr2=np.array([[2,4,5,7],[9,5,3,2]])
arr3=np.array([[[2,5,6],[3,5,9]],[[3,5,7],[8,3,2]]])
print(arr)
print(arr[1])
print("\n")
print(arr2)
print("\n")
print(arr3)

[1 3 4 5]
3


[[2 4 5 7]
 [9 5 3 2]]


[[[2 5 6]
  [3 5 9]]

 [[3 5 7]
  [8 3 2]]]


In [7]:
import numpy as np

arr=np.array([1,3,4,5])
arr2=np.array([[2,4,5,7],[9,5,3,2]])
arr3=np.array([[[2,5,6],[3,5,9]],[[3,5,7],[8,3,2]]])
print(arr)
print(arr[1])
print("\n")
print(arr2)
print(arr2[1,2])
print("\n")
print(arr3)

[1 3 4 5]
3


[[2 4 5 7]
 [9 5 3 2]]
3


[[[2 5 6]
  [3 5 9]]

 [[3 5 7]
  [8 3 2]]]


In [19]:
import numpy as np

arr=np.array([1,3,4,5])
arr2=np.array([[2,4,5,7],[9,5,3,2]])
arr3=np.array([[[2,5,6],[3,5,9]],[[3,5,7],[8,3,2]]])
print(arr)
print(arr[1])
print("\n")
print(arr2)
print(arr2[1,2])
print("\n")
print(arr3)
print(arr3[0,1,2])

[1 3 4 5]
3


[[2 4 5 7]
 [9 5 3 2]]
3


[[[2 5 6]
  [3 5 9]]

 [[3 5 7]
  [8 3 2]]]
9


In [29]:
import numpy as np

arr=np.array([1,3,4,5])
arr2=np.array([[2,4,5,7],[9,5,3,2]])
arr3=np.array([[[2,5,6],[3,5,9]],[[3,5,7],[8,3,2]]])
print(arr)
print(arr[1])
print("\n")
print(arr2)
print("\n")
print(arr2[0:1])
print("\n")
print(arr2[1:2])
print("\n")
print(arr3)

[1 3 4 5]
3


[[2 4 5 7]
 [9 5 3 2]]


[[2 4 5 7]]


[[9 5 3 2]]


[[[2 5 6]
  [3 5 9]]

 [[3 5 7]
  [8 3 2]]]


In [48]:
import numpy as np

arr=np.array([1,3,4,5])
arr2=np.array([[2,4,5,7],[9,5,3,2]])
arr3=np.array([[[2,5,6],[3,5,9]],[[3,5,7],[8,3,2]]])
print(arr)
print(arr[1])
print("\n")
print(arr2)
print(arr2[1,2])
print("\n")
print(arr3)
print(arr3[0,1,2])
print("\n")
print(arr3[0,1:2])
print("\n")
print(arr3[1,0:1])

[1 3 4 5]
3


[[2 4 5 7]
 [9 5 3 2]]
3


[[[2 5 6]
  [3 5 9]]

 [[3 5 7]
  [8 3 2]]]
9


[[3 5 9]]


[[3 5 7]]


In [49]:
import numpy as np
arr0=np.array(23)
print(arr0)

23


In [50]:
import numpy as np
arr0=np.array(23)
print(arr0.ndim)

0


In [54]:
import numpy as np

arr=np.array([1,3,4,5])
print(arr[-2])
print(arr.ndim)

4
1


In [57]:
import numpy as np

arr=np.array([[1,3],[4,5]])
print(arr[-2])
print(arr.shape)

[1 3]
(2, 2)


In [58]:
import numpy as np

arr=np.array([1,3,4,5])
arr2=arr.copy()
print(arr2)

[1 3 4 5]


In [63]:
import numpy as np

arr=np.array([1,3,4,5])
arr1=np.array([9,8,7,6])
arr3=np.concatenate((arr,arr1))
print(arr3)

[1 3 4 5 9 8 7 6]


In [64]:
import numpy as np

arr=np.array([1,3,4,5])
narr2=np.array_split(arr,2)
print(narr2)

[array([1, 3]), array([4, 5])]


In [65]:
import numpy as np

arr=np.array([1,3,4,5])
arr1=np.where(arr==2)
print(arr1)

(array([], dtype=int64),)


In [66]:
import numpy as np

arr=np.array([1,3,4,5])
arr1=np.where(arr==5)
print(arr1)

(array([3], dtype=int64),)


In [68]:
import numpy as np

arr=np.array([9,1,5,2])
print(np.sort(arr))

[1 2 5 9]


In [69]:
import numpy as np

arr=np.array([9,1,5,2])
arr1=np.array([9,8,7,6])
arr2=arr+arr1
print(arr2)

[18  9 12  8]


In [70]:
import numpy as np

arr=np.array([9,1,5,2,3,4,6,7])
newarr=arr.reshape(2,4)
print(newarr)

[[9 1 5 2]
 [3 4 6 7]]
