In [1]:
#Ques2 Program to demostrate fibonacci series using recursion
def fibonacci(num):
    if num <= 0:
        return []
    elif num == 1:
        return [0]
    elif num == 2:
        return [0, 1]
    else:
        fib_series = [0, 1]
        for i in range(2, num):
            fib_series.append(fib_series[-1] + fib_series[-2])
        return fib_series

num = int(input("Enter the number of terms for Fibonacci series: "))
fib_series = fibonacci(num)
print("Fibonacci series:")
print(fib_series)

Enter the number of terms for Fibonacci series:  9


Fibonacci series:
[0, 1, 1, 2, 3, 5, 8, 13, 21]


###### 

In [20]:
import numpy as np

arr0=np.array(23)
arr=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4],[5,6,7,8]])
arr3=np.array([[[1,2,3,5,6],[4,5,6,7,8]],[[1,2,3,6,7],[4,5,6,8,9]]])
arr4=np.array(["Hi","Hello"])
print(arr4.dtype)
print(arr0.ndim)
print(arr[1])
print("\n")
print(arr2)
print("\n")
print(arr2[1,3])
print("\n")
print(arr3)
print("\n")
print(arr3[1,1,2])
print(arr3.shape)
arr5=arr3.copy()
print(arr5)

<U5
0
2


[[1 2 3 4]
 [5 6 7 8]]


8


[[[1 2 3 5 6]
  [4 5 6 7 8]]

 [[1 2 3 6 7]
  [4 5 6 8 9]]]


6
(2, 2, 5)
[[[1 2 3 5 6]
  [4 5 6 7 8]]

 [[1 2 3 6 7]
  [4 5 6 8 9]]]


In [25]:
import numpy as np

arr1=np.array([1,2,3,4])
arr2=np.array([0,2,6,8])
newarr=np.concatenate((arr1,arr2))
print(newarr)
finalArr=np.where(arr1==4)
print(finalArr)
print(np.sort(arr2))

[1 2 3 4 0 2 6 8]
(array([3], dtype=int64),)
[0 2 6 8]
