In [5]:
"""Ques1 Consider warehouse inventory system. [2D Array]
    1. Create an array consisting of product code & corresponding quantity"""
import numpy as np

inventory=np.array([[1001,1002,1003,1004],[10,20,30,40]])

print("Inventory: ",inventory)


Inventory:  [[1001 1002 1003 1004]
 [  10   20   30   40]]


In [8]:
#2. Determine the dimension of the inventory array
import numpy as np

inventory=np.array([[1001,1002,1003,1004],[10,20,30,40]])

print("Inventory: ",inventory,"\n")
print("Dimension of inventory",inventory.ndim)

Inventory:  [[1001 1002 1003 1004]
 [  10   20   30   40]] 

Dimension of inventory 2


In [10]:
#3. Given a product code search through the array to find quantity of array index column stack
import numpy as np

inventory=np.array([[1001,1002,1003,1004],[10,20,30,40]])

print("Inventory: ",inventory,"\n")
print("Dimension of inventory",inventory.ndim,"\n")
print("product code with quantity: ",np.column_stack(inventory))

Inventory:  [[1001 1002 1003 1004]
 [  10   20   30   40]] 

Dimension of inventory 2 

product code with quantity:  [[1001   10]
 [1002   20]
 [1003   30]
 [1004   40]]


In [15]:
#4. Split the array to 2 arrays 
import numpy as np

inventory=np.array([[1001,1002,1003,1004],[10,20,30,40]])

print("Inventory: ",inventory,"\n")
print("Dimension of inventory",inventory.ndim,"\n")
print("product code with quantity: ",np.column_stack(inventory),"\n")
print("Spliting: ",np.array_split(inventory,2))

Inventory:  [[1001 1002 1003 1004]
 [  10   20   30   40]] 

Dimension of inventory 2 

product code with quantity:  [[1001   10]
 [1002   20]
 [1003   30]
 [1004   40]] 

Spliting:  [array([[1001, 1002, 1003, 1004]]), array([[10, 20, 30, 40]])]


In [18]:
# 5. Reterive the quantity using array index 
import numpy as np

inventory=np.array([[1001,1002,1003,1004],[10,20,30,40]])

print("Inventory: ",inventory,"\n")
print("Dimension of inventory",inventory.ndim,"\n")
print("product code with quantity: ",np.column_stack(inventory),"\n")
print("Spliting: ",np.array_split(inventory,2),"\n")
print("Quantity: ",inventory[1:2])

Inventory:  [[1001 1002 1003 1004]
 [  10   20   30   40]] 

Dimension of inventory 2 

product code with quantity:  [[1001   10]
 [1002   20]
 [1003   30]
 [1004   40]] 

Spliting:  [array([[1001, 1002, 1003, 1004]]), array([[10, 20, 30, 40]])] 

Quantity:  [[10 20 30 40]]


In [20]:
#6. Check the shape of the inventory array
import numpy as np

inventory=np.array([[1001,1002,1003,1004],[10,20,30,40]])

print("Inventory: ",inventory,"\n")
print("Dimension of inventory",inventory.ndim,"\n")
print("product code with quantity: ",np.column_stack(inventory),"\n")
print("Spliting: ",np.array_split(inventory,2),"\n")
print("Quantity: ",inventory[1:2],"\n")
print("Shape of array: ",inventory.shape)

Inventory:  [[1001 1002 1003 1004]
 [  10   20   30   40]] 

Dimension of inventory 2 

product code with quantity:  [[1001   10]
 [1002   20]
 [1003   30]
 [1004   40]] 

Spliting:  [array([[1001, 1002, 1003, 1004]]), array([[10, 20, 30, 40]])] 

Quantity:  [[10 20 30 40]] 

Shape of array:  (2, 4)


In [26]:
#7. reshape the inventory onto 2D array
import numpy as np

inventory=np.array([[1001,1002,1003,1004],[10,20,30,40]])

print("Inventory: ",inventory,"\n")
print("Dimension of inventory",inventory.ndim,"\n")
print("product code with quantity: ",np.column_stack(inventory),"\n")
print("Spliting: ",np.array_split(inventory,2),"\n")
print("Quantity: ",inventory[1:2],"\n")
print("Shape of array: ",inventory.shape,"\n")
newinventory=inventory.reshape(4,2)
print("Reshape of array: ",newinventory)

Inventory:  [[1001 1002 1003 1004]
 [  10   20   30   40]] 

Dimension of inventory 2 

product code with quantity:  [[1001   10]
 [1002   20]
 [1003   30]
 [1004   40]] 

Spliting:  [array([[1001, 1002, 1003, 1004]]), array([[10, 20, 30, 40]])] 

Quantity:  [[10 20 30 40]] 

Shape of array:  (2, 4) 

Reshape of array:  [[1001 1002]
 [1003 1004]
 [  10   20]
 [  30   40]]


In [1]:
#8. Create a copy of the inventory array
import numpy as np

inventory=np.array([[1001,1002,1003,1004],[10,20,30,40]])

print("Inventory: ",inventory,"\n")
print("Dimension of inventory",inventory.ndim,"\n")
print("product code with quantity: ",np.column_stack(inventory),"\n")
print("Spliting: ",np.array_split(inventory,2),"\n")
print("Quantity: ",inventory[1:2],"\n")
print("Shape of array: ",inventory.shape,"\n")
newinventory=inventory.reshape(4,2)
print("Reshape of array: ",newinventory,"\n")
updateinventory=inventory.copy()
print("Copy of inventory: ",updateinventory)

Inventory:  [[1001 1002 1003 1004]
 [  10   20   30   40]] 

Dimension of inventory 2 

product code with quantity:  [[1001   10]
 [1002   20]
 [1003   30]
 [1004   40]] 

Spliting:  [array([[1001, 1002, 1003, 1004]]), array([[10, 20, 30, 40]])] 

Quantity:  [[10 20 30 40]] 

Shape of array:  (2, 4) 

Reshape of array:  [[1001 1002]
 [1003 1004]
 [  10   20]
 [  30   40]] 

Copy of inventory:  [[1001 1002 1003 1004]
 [  10   20   30   40]]


In [3]:
#9. Add new items to the inventory
import numpy as np

inventory=np.array([[1001,1002,1003,1004],[10,20,30,40]])

print("Inventory: ",inventory,"\n")
print("Dimension of inventory",inventory.ndim,"\n")
print("product code with quantity: ",np.column_stack(inventory),"\n")
print("Spliting: ",np.array_split(inventory,2),"\n")
print("Quantity: ",inventory[1:2],"\n")
print("Shape of array: ",inventory.shape,"\n")
newinventory=inventory.reshape(4,2)
print("Reshape of array: ",newinventory,"\n")
updateinventory=inventory.copy()
print("Copy of inventory: ",updateinventory,"\n")
newitem=np.array([[1005,1006,1007,1008],[50,60,70,80]])
modifyinventory=np.concatenate((inventory,newitem))
print("Updated Inventory: ",modifyinventory)

Inventory:  [[1001 1002 1003 1004]
 [  10   20   30   40]] 

Dimension of inventory 2 

product code with quantity:  [[1001   10]
 [1002   20]
 [1003   30]
 [1004   40]] 

Spliting:  [array([[1001, 1002, 1003, 1004]]), array([[10, 20, 30, 40]])] 

Quantity:  [[10 20 30 40]] 

Shape of array:  (2, 4) 

Reshape of array:  [[1001 1002]
 [1003 1004]
 [  10   20]
 [  30   40]] 

Copy of inventory:  [[1001 1002 1003 1004]
 [  10   20   30   40]] 

Updated Inventory:  [[1001 1002 1003 1004]
 [  10   20   30   40]
 [1005 1006 1007 1008]
 [  50   60   70   80]]
